### ISSUE TITLE
ABI-incompatible language bindings are loaded unconditionally

### ISSUE THREAD

**Issue by mvidner** [yast/yast-core#20]
To facilitate implementing YaST modules in various languages, yast2-core loads the optional language binding libraries, `/usr/lib*/YaST2/plugin/libpy2lang_*.so`, packaged in `yast2-*-bindings.rpm`.

But these are loaded even when we have compiled an incompatible core (eg. lexer_comments, because of adding comment members to `YCode`) and want to run that from the working copy. This is the cause of @dmajda's crash. We've worked around it by using `./configure --prefix=/nosuchpath` in his WC. (Another workaround is to uninstall the bindings)

Also, IIUC, this was the cause of the crashes in Jenkins last week. @jreidinger can you confirm that and comment on my proposed solution?:

I think we should have a switch to enable/disable the language plugin loading. It should stay enabled by default for compatibility. I propose an environment variable, `Y2DISABLELANGUAGEPLUGINS=...`, to be checked in [Y2LanguageLoader::Y2LanguageLoader ()](https://github.com/yast/yast-core/blob/60f7fe4b8c7421e246d3776ad3a5870ec19d765d/liby2/src/Y2LanguageLoader.cc#L58).

**Comment by cwh42** [comment]
@mvidner is this 7-year-old bug still valid?

**Comment by mvidner** [comment]
Yes, it is valid, but not a problem in practice because we seldom touch the yast2-core API. The same problem is much more frequent in libyui so we should solve it there.
