### ISSUE TITLE
ag_ini do not delete file after writing the file

### ISSUE THREAD

**Issue by mchf** [yast/yast-core#74]
```
// Write a value into file
SCR::Write(".network.value.\"eth0\".IPADDR", "1")
SCR::Write(".network", nil)

// delete the file
SCR::Write(".network.section.\"eth0\"", nil)
SCR::Write(".network", nil)
```

In this case, `/etc/sysconfig/network/ifcfg-eth0` should be written (it is) and removed subsequently. But when the script is done, the file is still present.

**Comment by dgdavid** [comment]
As far as I can see, the initially described problem here was _fixed_ in https://github.com/yast/yast-network/pull/172.

But, this is about an issue almost 6 years ago and things has changed a lot for yast2-network. 

Do you think the issue still relevant?

**Comment by mchf** [comment]
I guess we can close it. We have workaround and slightly move things towards augeas in some cases.
