### ISSUE TITLE
Is yast4debian ready for production site?

### ISSUE THREAD

**Issue by topstarnetwork** [yast/yast-core#95]
Hello,
Is yast4debian ready for production site? https://github.com/yast4debian
Regards, Heather

**Comment by ancorgs** [comment]
I don't think so. Looks like that project never moved forward.

For more information about the relation of YaST with other distributions see http://lists.opensuse.org/yast-devel/2014-11/msg00052.html (insight: it will not work)

**Comment by mvidner** [comment]
Correct, it is not usable.

https://github.com/yast4debian even seems to be a fork without any commits of its own.
